/*
# Faraklit SaaS Schema — Subscriptions, Licenses, Devices, Payments, Activity, Audit

1. Purpose
   - Complete the SaaS backend: subscriptions, licenses, device management, payments/invoices, activity events, admin audit logs, and app version tracking.

2. New Tables
   - `subscriptions` — links a user (and optionally org) to a plan with status and date range.
   - `licenses` — individual license keys tied to a subscription, with status, device count, and date range.
   - `devices` — registered devices for a license/user (fingerprint, platform, last seen).
   - `payments` — payment records for subscription purchases/renewals.
   - `invoices` — invoice documents tied to payments.
   - `activity_events` — event-based activity tracking (feature usage, auth events). Stores only metadata, never legal document content.
   - `admin_audit_logs` — immutable audit trail of admin actions. Cannot be modified or deleted via normal RLS.
   - `app_versions` — desktop app version tracking (version, platform, release date, min supported version, active user count).

3. Security
   - RLS enabled on all tables.
   - Users can read/manage their own subscriptions, licenses, devices, payments, invoices.
   - Activity events: users can insert their own; users can read their own; admins can read all.
   - Admin audit logs: only admins can read; no user-level insert/update/delete (insert via SECURITY DEFINER function or service role only).
   - App versions: publicly readable; only admins can modify.
   - All admin-only write operations check `app_metadata.role = 'admin'`.

4. Notes
   - `activity_events.event_name` uses dotted notation (e.g., `user.login`, `feature.precedent_search.opened`).
   - `activity_events` deliberately does NOT store legal document content, search queries, or client names — only which feature was used.
   - `admin_audit_logs` has no UPDATE or DELETE policies, making it effectively append-only via the client.
   - `devices.device_fingerprint` is a unique identifier generated by the desktop app.
*/

-- SUBSCRIPTIONS
CREATE TABLE IF NOT EXISTS subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  organization_id uuid REFERENCES organizations(id) ON DELETE SET NULL,
  plan_id uuid NOT NULL REFERENCES plans(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'cancelled', 'expired')),
  started_at timestamptz NOT NULL DEFAULT now(),
  ends_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "subs_select_own_or_admin" ON subscriptions;
CREATE POLICY "subs_select_own_or_admin" ON subscriptions FOR SELECT
  TO authenticated USING (
    user_id = auth.uid()
    OR organization_id IN (SELECT id FROM organizations WHERE owner_id = auth.uid())
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

DROP POLICY IF EXISTS "subs_insert_own" ON subscriptions;
CREATE POLICY "subs_insert_own" ON subscriptions FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "subs_update_own_or_admin" ON subscriptions;
CREATE POLICY "subs_update_own_or_admin" ON subscriptions FOR UPDATE
  TO authenticated USING (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  ) WITH CHECK (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

-- LICENSES
CREATE TABLE IF NOT EXISTS licenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  license_key text UNIQUE NOT NULL DEFAULT upper(replace(gen_random_uuid()::text, '-', '')),
  subscription_id uuid NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  plan_id uuid NOT NULL REFERENCES plans(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'expired', 'cancelled')),
  started_at timestamptz NOT NULL DEFAULT now(),
  ends_at timestamptz NOT NULL,
  device_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE licenses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "licenses_select_own_or_admin" ON licenses;
CREATE POLICY "licenses_select_own_or_admin" ON licenses FOR SELECT
  TO authenticated USING (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

DROP POLICY IF EXISTS "licenses_insert_own" ON licenses;
CREATE POLICY "licenses_insert_own" ON licenses FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "licenses_update_own_or_admin" ON licenses;
CREATE POLICY "licenses_update_own_or_admin" ON licenses FOR UPDATE
  TO authenticated USING (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  ) WITH CHECK (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

-- DEVICES
CREATE TABLE IF NOT EXISTS devices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  license_id uuid NOT NULL REFERENCES licenses(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  device_name text NOT NULL DEFAULT '',
  device_fingerprint text NOT NULL,
  platform text NOT NULL DEFAULT 'windows' CHECK (platform IN ('windows', 'macos', 'linux')),
  app_version text DEFAULT '',
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (license_id, device_fingerprint)
);

ALTER TABLE devices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "devices_select_own_or_admin" ON devices;
CREATE POLICY "devices_select_own_or_admin" ON devices FOR SELECT
  TO authenticated USING (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

DROP POLICY IF EXISTS "devices_insert_own" ON devices;
CREATE POLICY "devices_insert_own" ON devices FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "devices_update_own_or_admin" ON devices;
CREATE POLICY "devices_update_own_or_admin" ON devices FOR UPDATE
  TO authenticated USING (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  ) WITH CHECK (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

DROP POLICY IF EXISTS "devices_delete_own_or_admin" ON devices;
CREATE POLICY "devices_delete_own_or_admin" ON devices FOR DELETE
  TO authenticated USING (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

-- PAYMENTS
CREATE TABLE IF NOT EXISTS payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  subscription_id uuid REFERENCES subscriptions(id) ON DELETE SET NULL,
  plan_id uuid NOT NULL REFERENCES plans(id) ON DELETE RESTRICT,
  order_number text UNIQUE NOT NULL DEFAULT ('FRK-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))),
  amount_cents integer NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'TRY',
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed', 'refunded')),
  provider text DEFAULT '',
  provider_payment_id text DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "payments_select_own_or_admin" ON payments;
CREATE POLICY "payments_select_own_or_admin" ON payments FOR SELECT
  TO authenticated USING (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

DROP POLICY IF EXISTS "payments_insert_own" ON payments;
CREATE POLICY "payments_insert_own" ON payments FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "payments_update_own_or_admin" ON payments;
CREATE POLICY "payments_update_own_or_admin" ON payments FOR UPDATE
  TO authenticated USING (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  ) WITH CHECK (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

-- INVOICES
CREATE TABLE IF NOT EXISTS invoices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  payment_id uuid NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  invoice_number text UNIQUE NOT NULL DEFAULT ('INV-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))),
  amount_cents integer NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'TRY',
  billing_name text DEFAULT '',
  billing_tax_id text DEFAULT '',
  billing_tax_office text DEFAULT '',
  billing_address text DEFAULT '',
  billing_city text DEFAULT '',
  billing_phone text DEFAULT '',
  billing_email text DEFAULT '',
  status text NOT NULL DEFAULT 'issued' CHECK (status IN ('issued', 'paid', 'void')),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "invoices_select_own_or_admin" ON invoices;
CREATE POLICY "invoices_select_own_or_admin" ON invoices FOR SELECT
  TO authenticated USING (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

DROP POLICY IF EXISTS "invoices_insert_own" ON invoices;
CREATE POLICY "invoices_insert_own" ON invoices FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());

-- ACTIVITY EVENTS
CREATE TABLE IF NOT EXISTS activity_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  organization_id uuid REFERENCES organizations(id) ON DELETE SET NULL,
  event_name text NOT NULL,
  app_version text DEFAULT '',
  platform text DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE activity_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "activity_select_own_or_admin" ON activity_events;
CREATE POLICY "activity_select_own_or_admin" ON activity_events FOR SELECT
  TO authenticated USING (
    user_id = auth.uid()
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

DROP POLICY IF EXISTS "activity_insert_own" ON activity_events;
CREATE POLICY "activity_insert_own" ON activity_events FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());

-- ADMIN AUDIT LOGS (append-only: no UPDATE or DELETE policies)
CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  action text NOT NULL,
  target_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  details text DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE admin_audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "audit_logs_select_admin" ON admin_audit_logs;
CREATE POLICY "audit_logs_select_admin" ON admin_audit_logs FOR SELECT
  TO authenticated USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

DROP POLICY IF EXISTS "audit_logs_insert_admin" ON admin_audit_logs;
CREATE POLICY "audit_logs_insert_admin" ON admin_audit_logs FOR INSERT
  TO authenticated WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- APP VERSIONS
CREATE TABLE IF NOT EXISTS app_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version text NOT NULL,
  platform text NOT NULL CHECK (platform IN ('windows', 'macos', 'linux')),
  release_date date NOT NULL DEFAULT CURRENT_DATE,
  min_supported_version text DEFAULT '',
  active_user_count integer NOT NULL DEFAULT 0,
  is_latest boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE app_versions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "versions_select_public" ON app_versions;
CREATE POLICY "versions_select_public" ON app_versions FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "versions_admin_write" ON app_versions;
CREATE POLICY "versions_admin_write" ON app_versions FOR INSERT
  TO authenticated WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

DROP POLICY IF EXISTS "versions_admin_update" ON app_versions;
CREATE POLICY "versions_admin_update" ON app_versions FOR UPDATE
  TO authenticated USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

DROP POLICY IF EXISTS "versions_admin_delete" ON app_versions;
CREATE POLICY "versions_admin_delete" ON app_versions FOR DELETE
  TO authenticated USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- Seed app versions
INSERT INTO app_versions (version, platform, release_date, min_supported_version, active_user_count, is_latest)
VALUES
  ('1.4.2', 'windows', '2026-08-24', '1.3.0', 317, true),
  ('1.4.2', 'macos', '2026-08-24', '1.3.0', 184, true),
  ('1.4.1', 'windows', '2026-07-15', '1.3.0', 42, false),
  ('1.4.0', 'macos', '2026-06-20', '1.2.0', 12, false)
ON CONFLICT DO NOTHING;

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_licenses_user_id ON licenses(user_id);
CREATE INDEX IF NOT EXISTS idx_licenses_status ON licenses(status);
CREATE INDEX IF NOT EXISTS idx_devices_user_id ON devices(user_id);
CREATE INDEX IF NOT EXISTS idx_devices_license_id ON devices(license_id);
CREATE INDEX IF NOT EXISTS idx_payments_user_id ON payments(user_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_invoices_user_id ON invoices(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_user_id ON activity_events(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_event_name ON activity_events(event_name);
CREATE INDEX IF NOT EXISTS idx_activity_created_at ON activity_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_admin_id ON admin_audit_logs(admin_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON admin_audit_logs(created_at DESC);
